### ISSUE TITLE
Build errors and some hints needed

### ISSUE THREAD

**Issue by rabser** [Devatoria/go-mesos-executor#48]
I'm trying to build go-mesos-executor, but i'm facing some fatal errors in go build:

```
./main.go:43:14: cannot use "go.uber.org/zap".String("executorID", executorID) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Info
./main.go:44:14: cannot use "go.uber.org/zap".String("frameworkID", frameworkID) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Info
./main.go:51:14: cannot use "go.uber.org/zap".Error(err) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Fatal
./main.go:58:15: cannot use "go.uber.org/zap".Reflect("hooks", hooks) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Info
./main.go:76:14: cannot use "go.uber.org/zap".Error(err) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Fatal
./main.go:137:13: cannot use "go.uber.org/zap".Error(err) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Fatal
./main.go:145:13: cannot use "go.uber.org/zap".Error(err) (type "go.uber.org/zap/zapcore".Field) as type "github.com/Devatoria/go-mesos-executor/vendor/go.uber.org/zap/zapcore".Field in argument to logger.GetInstance().Fatal

```

I'm not a go expert but these are the steps that i did:
git clone https://github.com/Devatoria/go-mesos-executor
cd go-mesos-executor
go get
go build

Where i'm wrong ?
I'm using "go version go1.9.4 linux/amd64" on Centos 7.x

**Another question**: how i can use the hooks from my custom scheduler ? I didn't find any doc about it.
I suppose that i need to add some params to the json, or i'm wrong ?

Thanks in advance for you kind support

**Comment by Devatoria** [comment]
Hi,

First, you should not have to go get since vendors are pushed in the repository. But it's not the problem. 

Where did you clone the repository? You should have cloned in $GOPATH/src/github.com/Devatoria/go-mesos-executor. Can you confirm it? Otherwise, imports would be broken.

For your other question, please note that, as explained in the disclaimer, this project is **not** an executor to use as is as a custom executor. It is a replacement of the base mesos-docker-executor, providing some other features. But, if you plan to develop a custom executor for your custom scheduler and need some help, I'd be happy to answer your questions :)

**Comment by rabser** [comment]
Thanks for your prompt reply.
I did the clone in my home ... Following your suggestions the go build it's now fine.

I would use this executor as a docker executor replacement for mesos, because i'm interested either in using the hooks provided by this executor (the standard mesos doesn't, right ?). 
My scheduler works sending tasks to "standard" DOCKER executor (substituted on each agent with the go-mesos-executor), but i don't understand where and how i have to put, for example, the pre-create command.
So not a custom executor, this is clear to me.

As per your instructions, i created a config.yaml in /etc/mesos-executor listing the pre-create in the enabled hooks.

**Comment by Devatoria** [comment]
The standard Docker mesos executor doesn't (AFAIK). But, Mesos allows you to create what they call modules, and that can do the trick as long as you're okay to write some cpp code. From my point of view, modules can be a better solution in many cases (for example, if you have to force tasks to be launched in non-privileged mode): http://mesos.apache.org/documentation/latest/modules/. Do not hesitate to take a look at them.

Also, do not hesitate to take a look at the executor designed by Allegro company. I met them during MesosCon Europe 2017 and they make very good job. https://github.com/allegro/mesos-executor

Regarding my project, you have to add a configuration file: `/etc/mesos-executor/config.yaml`. In this file, you have to provide a list of enabled hooks:

```
hooks: # Enabled hooks
  - removeContainer
  - netns
  - network
  - iptables
  - acl
```
Some hooks have a specific configuration. For example, for the netns hook:
```
netns:
  path: /var/run/netns # netns tool path
```

If you wish to create your own hooks, unfortunately, you have to dig in the code a little bit since they are part of the project.

I hope all those informations will help you.

**Comment by rabser** [comment]
thanks for suggestions, i dig into modules and isolators yet, but before launching myself in new code, i was investigating if there is yet solutions useful for my purposes: i would execute a bash command in the slave before the container is created.
Again, thanks for your time.

**Comment by rabser** [comment]
After getting myself more confident with Go language, i understood the programming logic behind the hooks, so now i wrote successfully (copying from the existing ones) a new hook instance and the things work as i need: amazing.

**Comment by Devatoria** [comment]
Nice :+1: 
Feel free to submit a PR if you want to make your hook public. I close this issue since it seems to be fixed. Do not hesitate to re-open if needed.
